<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>6.9 Deduplicación de registros | Fundamentos estadísticos para el análisis de las encuestas postcensales</title>
  <meta name="description" content="Encuestas Postcensales" />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="6.9 Deduplicación de registros | Fundamentos estadísticos para el análisis de las encuestas postcensales" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Encuestas Postcensales" />
  <meta name="github-repo" content="psirusteam/PESguidelines" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="6.9 Deduplicación de registros | Fundamentos estadísticos para el análisis de las encuestas postcensales" />
  
  <meta name="twitter:description" content="Encuestas Postcensales" />
  

<meta name="author" content="Andrés Gutiérrez, Giovany Babativa" />


<meta name="date" content="2025-09-08" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="implementación.html"/>
<link rel="next" href="vinculación-de-registros.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="libs/d3-3.3.8/d3.min.js"></script>
<script src="libs/dagre-0.4.0/dagre-d3.min.js"></script>
<link href="libs/mermaid-0.3.0/dist/mermaid.css" rel="stylesheet" />
<script src="libs/mermaid-0.3.0/dist/mermaid.slim.min.js"></script>
<link href="libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet" />
<script src="libs/chromatography-0.1/chromatography.js"></script>
<script src="libs/DiagrammeR-binding-1.0.11/DiagrammeR.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Encuestas postcensales</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Abstract</a></li>
<li class="chapter" data-level="1" data-path="cap-dual.html"><a href="cap-dual.html"><i class="fa fa-check"></i><b>1</b> El sistema de estimación dual</a>
<ul>
<li class="chapter" data-level="1.1" data-path="planteamiento-del-problema.html"><a href="planteamiento-del-problema.html"><i class="fa fa-check"></i><b>1.1</b> Planteamiento del problema</a></li>
<li class="chapter" data-level="1.2" data-path="condiciones-y-supuestos.html"><a href="condiciones-y-supuestos.html"><i class="fa fa-check"></i><b>1.2</b> Condiciones y supuestos</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="condiciones-y-supuestos.html"><a href="condiciones-y-supuestos.html#estabilidad-poblacional"><i class="fa fa-check"></i><b>1.2.1</b> Estabilidad poblacional</a></li>
<li class="chapter" data-level="1.2.2" data-path="condiciones-y-supuestos.html"><a href="condiciones-y-supuestos.html#sec:multinomial"><i class="fa fa-check"></i><b>1.2.2</b> Estructura multinomial</a></li>
<li class="chapter" data-level="1.2.3" data-path="condiciones-y-supuestos.html"><a href="condiciones-y-supuestos.html#independencia-autónoma"><i class="fa fa-check"></i><b>1.2.3</b> Independencia autónoma</a></li>
<li class="chapter" data-level="1.2.4" data-path="condiciones-y-supuestos.html"><a href="condiciones-y-supuestos.html#independencia-causal"><i class="fa fa-check"></i><b>1.2.4</b> Independencia causal</a></li>
<li class="chapter" data-level="1.2.5" data-path="condiciones-y-supuestos.html"><a href="condiciones-y-supuestos.html#emparejamiento"><i class="fa fa-check"></i><b>1.2.5</b> Emparejamiento</a></li>
<li class="chapter" data-level="1.2.6" data-path="condiciones-y-supuestos.html"><a href="condiciones-y-supuestos.html#eventos-espurios"><i class="fa fa-check"></i><b>1.2.6</b> Eventos espurios</a></li>
<li class="chapter" data-level="1.2.7" data-path="condiciones-y-supuestos.html"><a href="condiciones-y-supuestos.html#postestratificación"><i class="fa fa-check"></i><b>1.2.7</b> Postestratificación</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="inferencia.html"><a href="inferencia.html"><i class="fa fa-check"></i><b>1.3</b> Inferencia</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="inferencia.html"><a href="inferencia.html#los-estimadores-del-sistema-dual"><i class="fa fa-check"></i><b>1.3.1</b> Los estimadores del sistema dual</a></li>
<li class="chapter" data-level="1.3.2" data-path="inferencia.html"><a href="inferencia.html#propiedades-del-estimador"><i class="fa fa-check"></i><b>1.3.2</b> Propiedades del estimador</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="estimación-dual-con-la-muestra-de-la-encuesta.html"><a href="estimación-dual-con-la-muestra-de-la-encuesta.html"><i class="fa fa-check"></i><b>2</b> Estimación dual con la muestra de la encuesta</a>
<ul>
<li class="chapter" data-level="2.1" data-path="el-diseño-de-muestreo.html"><a href="el-diseño-de-muestreo.html"><i class="fa fa-check"></i><b>2.1</b> El diseño de muestreo</a></li>
<li class="chapter" data-level="2.2" data-path="la-muestra-e-y-la-muestra-p.html"><a href="la-muestra-e-y-la-muestra-p.html"><i class="fa fa-check"></i><b>2.2</b> La muestra E y la muestra P</a></li>
<li class="chapter" data-level="2.3" data-path="los-estimadores-de-muestreo.html"><a href="los-estimadores-de-muestreo.html"><i class="fa fa-check"></i><b>2.3</b> Los estimadores de muestreo</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="cap3.html"><a href="cap3.html"><i class="fa fa-check"></i><b>3</b> Enumeraciones y procedimientos</a>
<ul>
<li class="chapter" data-level="3.1" data-path="enumeraciones-correctas-con-la-muestra-e.html"><a href="enumeraciones-correctas-con-la-muestra-e.html"><i class="fa fa-check"></i><b>3.1</b> Enumeraciones correctas con la muestra E</a></li>
<li class="chapter" data-level="3.2" data-path="sec-procedimientos.html"><a href="sec-procedimientos.html"><i class="fa fa-check"></i><b>3.2</b> Reconstrucción de los hogares con la muestra P</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="sec-procedimientos.html"><a href="sec-procedimientos.html#procedimiento-a"><i class="fa fa-check"></i><b>3.2.1</b> Procedimiento A</a></li>
<li class="chapter" data-level="3.2.2" data-path="sec-procedimientos.html"><a href="sec-procedimientos.html#procedimiento-b"><i class="fa fa-check"></i><b>3.2.2</b> Procedimiento B</a></li>
<li class="chapter" data-level="3.2.3" data-path="sec-procedimientos.html"><a href="sec-procedimientos.html#procedimiento-c"><i class="fa fa-check"></i><b>3.2.3</b> Procedimiento C</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="cap-estim.html"><a href="cap-estim.html"><i class="fa fa-check"></i><b>4</b> Estimadores del sistema dual</a>
<ul>
<li class="chapter" data-level="4.1" data-path="estimador-de-petersen.html"><a href="estimador-de-petersen.html"><i class="fa fa-check"></i><b>4.1</b> Estimador de Petersen</a></li>
<li class="chapter" data-level="4.2" data-path="estimador-de-chapman.html"><a href="estimador-de-chapman.html"><i class="fa fa-check"></i><b>4.2</b> Estimador de Chapman</a></li>
<li class="chapter" data-level="4.3" data-path="estimador-de-nour.html"><a href="estimador-de-nour.html"><i class="fa fa-check"></i><b>4.3</b> Estimador de Nour</a></li>
<li class="chapter" data-level="4.4" data-path="estimador-de-chao.html"><a href="estimador-de-chao.html"><i class="fa fa-check"></i><b>4.4</b> Estimador de Chao</a></li>
<li class="chapter" data-level="4.5" data-path="estimador-de-webster-kemp.html"><a href="estimador-de-webster-kemp.html"><i class="fa fa-check"></i><b>4.5</b> Estimador de Webster-Kemp</a></li>
<li class="chapter" data-level="4.6" data-path="estimador-de-zelterman.html"><a href="estimador-de-zelterman.html"><i class="fa fa-check"></i><b>4.6</b> Estimador de Zelterman</a></li>
<li class="chapter" data-level="4.7" data-path="modelos-log-lineales.html"><a href="modelos-log-lineales.html"><i class="fa fa-check"></i><b>4.7</b> Modelos log-lineales</a></li>
<li class="chapter" data-level="4.8" data-path="otros-modelos.html"><a href="otros-modelos.html"><i class="fa fa-check"></i><b>4.8</b> Otros modelos</a></li>
<li class="chapter" data-level="4.9" data-path="notas-adicionales.html"><a href="notas-adicionales.html"><i class="fa fa-check"></i><b>4.9</b> Notas adicionales</a></li>
<li class="chapter" data-level="4.10" data-path="cuadro-comparativo-de-los-estimadores.html"><a href="cuadro-comparativo-de-los-estimadores.html"><i class="fa fa-check"></i><b>4.10</b> Cuadro comparativo de los estimadores</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="evaluación-de-la-cobertura-censal.html"><a href="evaluación-de-la-cobertura-censal.html"><i class="fa fa-check"></i><b>5</b> Evaluación de la cobertura censal</a>
<ul>
<li class="chapter" data-level="5.1" data-path="objetivos-de-la-encuesta-postcensal.html"><a href="objetivos-de-la-encuesta-postcensal.html"><i class="fa fa-check"></i><b>5.1</b> Objetivos de la encuesta postcensal</a></li>
<li class="chapter" data-level="5.2" data-path="componentes-de-la-cobertura-censal.html"><a href="componentes-de-la-cobertura-censal.html"><i class="fa fa-check"></i><b>5.2</b> Componentes de la cobertura censal</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="componentes-de-la-cobertura-censal.html"><a href="componentes-de-la-cobertura-censal.html#enumeraciones-correctas"><i class="fa fa-check"></i><b>5.2.1</b> Enumeraciones correctas</a></li>
<li class="chapter" data-level="5.2.2" data-path="componentes-de-la-cobertura-censal.html"><a href="componentes-de-la-cobertura-censal.html#enumeraciones-erróneas"><i class="fa fa-check"></i><b>5.2.2</b> Enumeraciones erróneas</a></li>
<li class="chapter" data-level="5.2.3" data-path="componentes-de-la-cobertura-censal.html"><a href="componentes-de-la-cobertura-censal.html#omisiones"><i class="fa fa-check"></i><b>5.2.3</b> Omisiones</a></li>
<li class="chapter" data-level="5.2.4" data-path="componentes-de-la-cobertura-censal.html"><a href="componentes-de-la-cobertura-censal.html#imputación"><i class="fa fa-check"></i><b>5.2.4</b> Imputación</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="protocolo-de-clasificación.html"><a href="protocolo-de-clasificación.html"><i class="fa fa-check"></i><b>5.3</b> Protocolo de clasificación</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="protocolo-de-clasificación.html"><a href="protocolo-de-clasificación.html#preprocesamiento-de-datos"><i class="fa fa-check"></i><b>5.3.1</b> Preprocesamiento de datos</a></li>
<li class="chapter" data-level="5.3.2" data-path="protocolo-de-clasificación.html"><a href="protocolo-de-clasificación.html#emparejamiento-de-registros"><i class="fa fa-check"></i><b>5.3.2</b> Emparejamiento de registros</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="flujo-general-del-procedimiento.html"><a href="flujo-general-del-procedimiento.html"><i class="fa fa-check"></i><b>5.4</b> Flujo general del procedimiento</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="emparejamiento-probabilístico.html"><a href="emparejamiento-probabilístico.html"><i class="fa fa-check"></i><b>6</b> Emparejamiento probabilístico</a>
<ul>
<li class="chapter" data-level="6.1" data-path="geolocalización.html"><a href="geolocalización.html"><i class="fa fa-check"></i><b>6.1</b> Geolocalización</a></li>
<li class="chapter" data-level="6.2" data-path="flujo-general.html"><a href="flujo-general.html"><i class="fa fa-check"></i><b>6.2</b> Flujo general</a></li>
<li class="chapter" data-level="6.3" data-path="preprocesamiento.html"><a href="preprocesamiento.html"><i class="fa fa-check"></i><b>6.3</b> Preprocesamiento</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="preprocesamiento.html"><a href="preprocesamiento.html#limpieza-de-los-datos"><i class="fa fa-check"></i><b>6.3.1</b> Limpieza de los datos</a></li>
<li class="chapter" data-level="6.3.2" data-path="preprocesamiento.html"><a href="preprocesamiento.html#codificación-fonética"><i class="fa fa-check"></i><b>6.3.2</b> Codificación fonética</a></li>
<li class="chapter" data-level="6.3.3" data-path="preprocesamiento.html"><a href="preprocesamiento.html#metaphone"><i class="fa fa-check"></i><b>6.3.3</b> Metaphone</a></li>
<li class="chapter" data-level="6.3.4" data-path="preprocesamiento.html"><a href="preprocesamiento.html#algoritmo-statistics-canada"><i class="fa fa-check"></i><b>6.3.4</b> Algoritmo Statistics Canada</a></li>
<li class="chapter" data-level="6.3.5" data-path="preprocesamiento.html"><a href="preprocesamiento.html#adaptación-para-encuestas-de-américa-latina"><i class="fa fa-check"></i><b>6.3.5</b> Adaptación para Encuestas de América Latina</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="indexación.html"><a href="indexación.html"><i class="fa fa-check"></i><b>6.4</b> Indexación</a></li>
<li class="chapter" data-level="6.5" data-path="comparación.html"><a href="comparación.html"><i class="fa fa-check"></i><b>6.5</b> Comparación</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="comparación.html"><a href="comparación.html#distancia-de-levenshtein"><i class="fa fa-check"></i><b>6.5.1</b> Distancia de Levenshtein</a></li>
<li class="chapter" data-level="6.5.2" data-path="comparación.html"><a href="comparación.html#comparación-de-jaro-y-winkler"><i class="fa fa-check"></i><b>6.5.2</b> Comparación de Jaro y Winkler</a></li>
<li class="chapter" data-level="6.5.3" data-path="comparación.html"><a href="comparación.html#comparación-de-fechas-y-edades"><i class="fa fa-check"></i><b>6.5.3</b> Comparación de fechas y edades</a></li>
<li class="chapter" data-level="6.5.4" data-path="comparación.html"><a href="comparación.html#comparación-geográfica"><i class="fa fa-check"></i><b>6.5.4</b> Comparación geográfica</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="clasificación.html"><a href="clasificación.html"><i class="fa fa-check"></i><b>6.6</b> Clasificación</a></li>
<li class="chapter" data-level="6.7" data-path="evaluación.html"><a href="evaluación.html"><i class="fa fa-check"></i><b>6.7</b> Evaluación</a>
<ul>
<li class="chapter" data-level="6.7.1" data-path="evaluación.html"><a href="evaluación.html#métricas-de-desempeño"><i class="fa fa-check"></i><b>6.7.1</b> Métricas de desempeño</a></li>
<li class="chapter" data-level="6.7.2" data-path="evaluación.html"><a href="evaluación.html#métricas-de-eficiencia"><i class="fa fa-check"></i><b>6.7.2</b> Métricas de eficiencia</a></li>
<li class="chapter" data-level="6.7.3" data-path="evaluación.html"><a href="evaluación.html#revisión-clerical"><i class="fa fa-check"></i><b>6.7.3</b> Revisión clerical</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="implementación.html"><a href="implementación.html"><i class="fa fa-check"></i><b>6.8</b> Implementación</a></li>
<li class="chapter" data-level="6.9" data-path="deduplicación-de-registros.html"><a href="deduplicación-de-registros.html"><i class="fa fa-check"></i><b>6.9</b> Deduplicación de registros</a></li>
<li class="chapter" data-level="6.10" data-path="vinculación-de-registros.html"><a href="vinculación-de-registros.html"><i class="fa fa-check"></i><b>6.10</b> Vinculación de registros</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="planeación-de-la-operación-estadística.html"><a href="planeación-de-la-operación-estadística.html"><i class="fa fa-check"></i><b>7</b> Planeación de la operación estadística</a>
<ul>
<li class="chapter" data-level="7.1" data-path="diseño-del-cuestionario.html"><a href="diseño-del-cuestionario.html"><i class="fa fa-check"></i><b>7.1</b> Diseño del cuestionario</a></li>
<li class="chapter" data-level="7.2" data-path="diseño-de-la-muestra.html"><a href="diseño-de-la-muestra.html"><i class="fa fa-check"></i><b>7.2</b> Diseño de la muestra</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="diseño-de-la-muestra.html"><a href="diseño-de-la-muestra.html#marco-de-muestreo"><i class="fa fa-check"></i><b>7.2.1</b> Marco de muestreo</a></li>
<li class="chapter" data-level="7.2.2" data-path="diseño-de-la-muestra.html"><a href="diseño-de-la-muestra.html#construcción-de-las-upm"><i class="fa fa-check"></i><b>7.2.2</b> Construcción de las UPM</a></li>
<li class="chapter" data-level="7.2.3" data-path="diseño-de-la-muestra.html"><a href="diseño-de-la-muestra.html#estratos"><i class="fa fa-check"></i><b>7.2.3</b> Estratos</a></li>
<li class="chapter" data-level="7.2.4" data-path="diseño-de-la-muestra.html"><a href="diseño-de-la-muestra.html#diseño-de-muestreo"><i class="fa fa-check"></i><b>7.2.4</b> Diseño de muestreo</a></li>
<li class="chapter" data-level="7.2.5" data-path="diseño-de-la-muestra.html"><a href="diseño-de-la-muestra.html#diseño-de-muestreo-estándar"><i class="fa fa-check"></i><b>7.2.5</b> Diseño de muestreo estándar</a></li>
<li class="chapter" data-level="7.2.6" data-path="diseño-de-la-muestra.html"><a href="diseño-de-la-muestra.html#cálculo-del-tamaño-de-muestra"><i class="fa fa-check"></i><b>7.2.6</b> Cálculo del tamaño de muestra</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="operativo-de-recolección.html"><a href="operativo-de-recolección.html"><i class="fa fa-check"></i><b>7.3</b> Operativo de recolección</a></li>
<li class="chapter" data-level="7.4" data-path="indicadores-principales.html"><a href="indicadores-principales.html"><i class="fa fa-check"></i><b>7.4</b> Indicadores principales</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="cap-reg.html"><a href="cap-reg.html"><i class="fa fa-check"></i><b>8</b> Modelos de regresión en el sistema dual</a>
<ul>
<li class="chapter" data-level="8.1" data-path="post-estratificación.html"><a href="post-estratificación.html"><i class="fa fa-check"></i><b>8.1</b> Post-estratificación</a></li>
<li class="chapter" data-level="8.2" data-path="regresión-logística.html"><a href="regresión-logística.html"><i class="fa fa-check"></i><b>8.2</b> Regresión logística</a></li>
<li class="chapter" data-level="8.3" data-path="ajuste-por-información-demográfica.html"><a href="ajuste-por-información-demográfica.html"><i class="fa fa-check"></i><b>8.3</b> Ajuste por información demográfica</a></li>
</ul></li>
<li class="divider"></li>
<li><a Encuestas postcensales </a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Fundamentos estadísticos para el análisis de las encuestas postcensales</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="deduplicación-de-registros" class="section level2 hasAnchor" number="6.9">
<h2><span class="header-section-number">6.9</span> Deduplicación de registros<a href="deduplicación-de-registros.html#deduplicación-de-registros" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Una etapa clave en el cálculo de la omisión censal, es asegurar que la base de enumeración de la PES no tiene duplicados. Poder identificar si una persona ha sido enumerada más de una vez en el censo, se conoce como proceso de deduplicación.</p>
<p><strong>Ejemplo usando el paquete RecordLinkage</strong></p>
<p>Para ilustrar este procedimiento se implementará un análisis supervisado utilizando los datos simulados <code>RLdata500</code> incluidos en el paquete <code>RecordLinkage</code>. El conjunto de datos contiene 500 registros simulados, incluyendo nombres, apellidos, fechas de nacimiento y un identificador de la persona real (<code>identity.RLdata500</code>). Suponga que este es un conjunto de entrenamiento que fue seleccionado con unos registros del censo, y en el cual se realizó un proceso de identificación y revisión clerical para identificar con certeza si un registro es duplicado o no, de esta manera es posible entrenar un modelo, realizar evaluaciones de precisión y entender mejor las decisiones del algoritmo.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="deduplicación-de-registros.html#cb23-1" tabindex="-1"></a><span class="fu">library</span>(RecordLinkage)</span>
<span id="cb23-2"><a href="deduplicación-de-registros.html#cb23-2" tabindex="-1"></a><span class="fu">data</span>(RLdata500)</span>
<span id="cb23-3"><a href="deduplicación-de-registros.html#cb23-3" tabindex="-1"></a><span class="fu">head</span>(RLdata500)</span></code></pre></div>
<pre><code>##   fname_c1 fname_c2 lname_c1 lname_c2   by bm bd
## 1  CARSTEN     &lt;NA&gt;    MEIER     &lt;NA&gt; 1949  7 22
## 2     GERD     &lt;NA&gt;    BAUER     &lt;NA&gt; 1968  7 27
## 3   ROBERT     &lt;NA&gt; HARTMANN     &lt;NA&gt; 1930  4 30
## 4   STEFAN     &lt;NA&gt;    WOLFF     &lt;NA&gt; 1957  9  2
## 5     RALF     &lt;NA&gt;  KRUEGER     &lt;NA&gt; 1966  1 13
## 6  JUERGEN     &lt;NA&gt;   FRANKE     &lt;NA&gt; 1929  7  4</code></pre>
<p>En caso de realizar todas la comparaciones por pares, serían necesarias 124.750 comparaciones:</p>
<p><span class="math display">\[\binom{500}{2} = 124.750\]</span>
Lo anterior es manejable en conjuntos de datos pequeños, pero en los casos de censos o encuestas de cobertura no resulta viable aplicar el total de comparaciones, por lo que será necesario realizar una indexación con unos bloques de comparación.</p>
<p>Como se ha mencionado antes, el bloqueo consiste en agrupar los registros en bloques más pequeños usando una o más variables, de manera que solo se comparan registros dentro del mismo bloque. En este ejemplo se usará la primera letra del apellido como clave de bloqueo.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="deduplicación-de-registros.html#cb25-1" tabindex="-1"></a>inic_apell <span class="ot">&lt;-</span> <span class="fu">substr</span>(RLdata500[,<span class="st">&quot;lname_c1&quot;</span>], <span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb25-2"><a href="deduplicación-de-registros.html#cb25-2" tabindex="-1"></a>(tbl <span class="ot">&lt;-</span> <span class="fu">table</span>(inic_apell))</span></code></pre></div>
<pre><code>## inic_apell
##   A   B   D   E   F   G   H   J   K   L   M   N   O   P   R   S   T   V   W   Z 
##   5  56   2   6  38  12  32   8  46  13  76   8   4   6   7 115   2   7  52   5</code></pre>
<p>Lo anterior genera 20 bloques, donde el número de registros por bloque puede ser diferente. Como ahora el número de comparaciones se realiza dentro de cada bloque, esto reduce drásticamente el número total de comparaciones que se tienen que realizar. Sin embargo, es recomendable evitar una alta variación en el número de registros por bloque, esto debido a que algunos bloques con un alto número de registros puede incremetar fuertemente el costo computacional. En este caso el número de registros por bloque varía entre 2 y 115.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="deduplicación-de-registros.html#cb27-1" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">as.numeric</span>(<span class="fu">table</span>(inic_apell)))</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    2.00    5.75    8.00   25.00   40.00  115.00</code></pre>
<p>A pesar de lo anterior, el número de pares posibles tras aplicar el bloqueo baja de 124750 a 14805 pares. Esta reducción es crucial para el rendimiento computacional del algoritmo. A continuación se observa el número de comparaciones por bloque.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="deduplicación-de-registros.html#cb29-1" tabindex="-1"></a><span class="fu">sapply</span>(tbl, choose, <span class="at">k=</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>##    A    B    D    E    F    G    H    J    K    L    M    N    O    P    R    S 
##   10 1540    1   15  703   66  496   28 1035   78 2850   28    6   15   21 6555 
##    T    V    W    Z 
##    1   21 1326   10</code></pre>
<p>Para entrenar el modelo, se agrega a la tabla de datos el id de cada persona y se quita la información redundante:</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="deduplicación-de-registros.html#cb31-1" tabindex="-1"></a>RLdata500c <span class="ot">&lt;-</span> RLdata500 <span class="sc">|&gt;</span>  </span>
<span id="cb31-2"><a href="deduplicación-de-registros.html#cb31-2" tabindex="-1"></a>              <span class="fu">mutate</span>(<span class="at">id =</span> identity.RLdata500) <span class="sc">|&gt;</span> </span>
<span id="cb31-3"><a href="deduplicación-de-registros.html#cb31-3" tabindex="-1"></a>              <span class="fu">select</span>(<span class="sc">-</span>fname_c2, <span class="sc">-</span>lname_c2)</span></code></pre></div>
<p>Ahora es sencillo filtrar los duplicados reales, esto permite examinar cómo se presentan las inconsistencias reales en los datos y elegir los métodos más apropiados en el entrenamiento del modelo.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="deduplicación-de-registros.html#cb32-1" tabindex="-1"></a>dup_set <span class="ot">&lt;-</span> RLdata500c <span class="sc">|&gt;</span> </span>
<span id="cb32-2"><a href="deduplicación-de-registros.html#cb32-2" tabindex="-1"></a>           <span class="fu">group_by</span>(id) <span class="sc">|&gt;</span> </span>
<span id="cb32-3"><a href="deduplicación-de-registros.html#cb32-3" tabindex="-1"></a>           <span class="fu">filter</span>(<span class="fu">n</span>() <span class="sc">&gt;</span> <span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb32-4"><a href="deduplicación-de-registros.html#cb32-4" tabindex="-1"></a>           <span class="fu">ungroup</span>() <span class="sc">|&gt;</span> </span>
<span id="cb32-5"><a href="deduplicación-de-registros.html#cb32-5" tabindex="-1"></a>           <span class="fu">arrange</span>(id)</span>
<span id="cb32-6"><a href="deduplicación-de-registros.html#cb32-6" tabindex="-1"></a></span>
<span id="cb32-7"><a href="deduplicación-de-registros.html#cb32-7" tabindex="-1"></a><span class="fu">tail</span>(dup_set)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 6
##   fname_c1  lname_c1    by    bm    bd    id
##   &lt;chr&gt;     &lt;chr&gt;    &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;dbl&gt;
## 1 RENATE    SCHUTE    1940    12    29   436
## 2 RENATE    SCHULTE   1940    12    29   436
## 3 CHRISTINE PETERS    1993     2     5   442
## 4 CHRISTINE PETERS    1993     2     6   442
## 5 CHRISTA   SCHWARZ   1965     7    13   444
## 6 CHRISTAH  SCHWARZ   1965     7    13   444</code></pre>
<p>Al calcular la distancia de Levenshtein observamos que la similaridad aún está lejana de 1, mientras que la métrica de Jaro y Winkler produce un mejor resultado de la similaridad.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="deduplicación-de-registros.html#cb34-1" tabindex="-1"></a><span class="fu">levenshteinSim</span>(<span class="fu">c</span>(<span class="st">&quot;SCHUTE&quot;</span>, <span class="st">&quot;SCHULTE&quot;</span>),</span>
<span id="cb34-2"><a href="deduplicación-de-registros.html#cb34-2" tabindex="-1"></a>               <span class="fu">c</span>(<span class="st">&quot;CHRISTA&quot;</span>, <span class="st">&quot;CHRISTAH&quot;</span>))</span></code></pre></div>
<pre><code>## [1] 0.2857143 0.2500000</code></pre>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="deduplicación-de-registros.html#cb36-1" tabindex="-1"></a><span class="fu">jarowinkler</span>(<span class="fu">c</span>(<span class="st">&quot;SCHUTE&quot;</span>, <span class="st">&quot;SCHULTE&quot;</span>),</span>
<span id="cb36-2"><a href="deduplicación-de-registros.html#cb36-2" tabindex="-1"></a>            <span class="fu">c</span>(<span class="st">&quot;CHRISTA&quot;</span>, <span class="st">&quot;CHRISTAH&quot;</span>))</span></code></pre></div>
<pre><code>## [1] 0.6428571 0.6011905</code></pre>
<p>El algoritmo de Jaro-Winkler tiende a funcionar mejor cuando los errores son de tipeo o diferencias leves. También se puede aplicar codificación fonética como <code>soundex()</code> o cualquiera de las presentadas en este capítulo.</p>
<p>En el siguiente paso se realiza la comparación de pares con bloqueo supervisado, toda vez que el resultado que identifica si es un duplicado o no es observado. La función <code>compare.dedup()</code> crea un objeto con la comparación entre pares de registros dentro de cada bloque. En este ejemplo se generan pares comparables según los bloques definidos por la primera letra del nombre y año de nacimiento (posiciones 1 y 3). Cada par se compara por igualdad de campos y similitud textual cuando se especifica.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="deduplicación-de-registros.html#cb38-1" tabindex="-1"></a>entrenamiento <span class="ot">&lt;-</span> <span class="fu">compare.dedup</span>(RLdata500c[,<span class="sc">-</span><span class="dv">6</span>], </span>
<span id="cb38-2"><a href="deduplicación-de-registros.html#cb38-2" tabindex="-1"></a>                               <span class="at">blockfld =</span> <span class="fu">list</span>(<span class="dv">1</span>, <span class="dv">3</span>),  </span>
<span id="cb38-3"><a href="deduplicación-de-registros.html#cb38-3" tabindex="-1"></a>                               <span class="at">identity =</span> identity.RLdata500)</span></code></pre></div>
<p>Ahora se calculan pesos probabilísticos para cada par comparado. Este paso estima la probabilidad de que cada par sea un match verdadero, usando un modelo probabilístico basado en la teoría de Fellegi-Sunter.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="deduplicación-de-registros.html#cb39-1" tabindex="-1"></a>prob <span class="ot">&lt;-</span> <span class="fu">epiWeights</span>(entrenamiento)</span></code></pre></div>
<p>A partir de las probabilidades se clasifica automáticamente los pares en tres categorías:</p>
<ul>
<li><strong>P</strong>: Positivo (match verdadero).</li>
<li><strong>N</strong>: Negativo (no match).</li>
<li><strong>L</strong>: Incertidumbre (requiere revisión clerical).</li>
</ul>
<p>En este caso se especifica un umbral de 0.7, es decir, los pares con probabilidad superior a ese valor se clasifican como positivos.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="deduplicación-de-registros.html#cb40-1" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">epiClassify</span>(prob, <span class="fl">0.7</span>)</span>
<span id="cb40-2"><a href="deduplicación-de-registros.html#cb40-2" tabindex="-1"></a><span class="fu">summary</span>(res)</span></code></pre></div>
<pre><code>## 
## Deduplication Data Set
## 
## 500 records 
## 2709 record pairs 
## 
## 50 matches
## 2659 non-matches
## 0 pairs with unknown status
## 
## 
## Weight distribution:
## 
## [0.2,0.25] (0.25,0.3] (0.3,0.35] (0.35,0.4] (0.4,0.45] (0.45,0.5] (0.5,0.55] 
##       2318          0        114        131         30         50          8 
## (0.55,0.6] (0.6,0.65] (0.65,0.7] (0.7,0.75] (0.75,0.8] (0.8,0.85] (0.85,0.9] 
##          2         10          0          0         35          8          3 
## 
## 46 links detected 
## 0 possible links detected 
## 2663 non-links detected 
## 
## alpha error: 0.080000
## beta error: 0.000000
## accuracy: 0.998523
## 
## 
## Classification table:
## 
##            classification
## true status    N    P    L
##       FALSE 2659    0    0
##       TRUE     4    0   46</code></pre>
<p>Se observa que la gran mayoría de los pares comparados presentan baja evidencia de coincidencia, con 2318 pares concentrados en el intervalo de peso [0.2, 0.25]. Por otra parte, solo 46 pares alcanzan un peso mayor a 0.7, lo que sugiere una alta probabilidad de ser duplicados.</p>
<p>Según la matriz de clasificación, de los 50 pares realmente duplicados, el modelo identificó correctamente a 46, mientras que 4 no fueron detectados, lo que corresponde a una tasa de falsos negativos de <span class="math inline">\(\alpha = 8\)</span>%. Por otro lado, la tasa de falsos positivos es cero, ya que ningún par no duplicado fue clasificado erróneamente como duplicado.</p>
<p>En conjunto, el modelo alcanzó una exactitud del 99.85%, lo que indica un alto rendimiento en la tarea de deduplicación.</p>
<p>Una vez se ha entrenado el modelo, se puede aplicar una comparación difusa (fuzzy) a todos los datos, para ampliar las posibilidades del ejemplo se usará con la métrica de Jaro-Winkler para todas las variables de cadena (<code>strcmp = TRUE</code>). Se omite el uso de funciones fonéticas (<code>phonetic = FALSE</code>), lo cual es útil cuando queremos detectar errores ortográficos leves y los bloques se arman solo por año de nacimiento. Aunque en la práctica se debe especificar el modelo entrenado.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="deduplicación-de-registros.html#cb42-1" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">compare.dedup</span>(RLdata500c[,<span class="sc">-</span><span class="dv">6</span>],</span>
<span id="cb42-2"><a href="deduplicación-de-registros.html#cb42-2" tabindex="-1"></a>                        <span class="at">phonetic =</span> <span class="cn">FALSE</span>,</span>
<span id="cb42-3"><a href="deduplicación-de-registros.html#cb42-3" tabindex="-1"></a>                        <span class="at">blockfld =</span> <span class="fu">list</span>(<span class="dv">1</span>, <span class="dv">3</span>),</span>
<span id="cb42-4"><a href="deduplicación-de-registros.html#cb42-4" tabindex="-1"></a>                        <span class="at">strcmp =</span> <span class="cn">TRUE</span>,</span>
<span id="cb42-5"><a href="deduplicación-de-registros.html#cb42-5" tabindex="-1"></a>                        <span class="at">strcmpfun =</span> jarowinkler)</span></code></pre></div>
<p>En conclusión, el uso de bloqueo combinado con comparaciones textuales permite reducir significativamente el esfuerzo computacional, en este caso, más del 90%, al evitar comparaciones innecesarias entre todos los registros. Además, este enfoque es efectivo para detectar duplicados incluso cuando existen errores de tipeo o inconsistencias en los datos, logrando una clasificación precisa de los pares potencialmente duplicados.</p>
<p>Se recomienda ajustar adecuadamente el argumento blockfld para optimizar la eficiencia del proceso, y seleccionar el método de comparación textual (por ejemplo, Jaro-Winkler o Levenshtein) de acuerdo con la calidad y naturaleza de los nombres en los datos.</p>
<p>Finalmente, es importante validar los resultados obtenidos, ya sea mediante revisión clerical o a través de otras reglas, para asegurar la confiabilidad del proceso de deduplicación.</p>
<p><strong>Ejemplo usando el paquete fastLink</strong></p>
<p>Para explorar otras opciones, en este ejemplo se usará el conjunto de datos <code>RLdata10000</code> del paquete <code>RecordLinkage</code>, el cual contiene 10.000 registros con 1.000 duplicados y 8.000 no duplicados.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="deduplicación-de-registros.html#cb43-1" tabindex="-1"></a><span class="fu">library</span>(pacman)</span>
<span id="cb43-2"><a href="deduplicación-de-registros.html#cb43-2" tabindex="-1"></a><span class="fu">p_load</span>(tidyverse, janitor, fastLink, RecordLinkage, parallel)</span>
<span id="cb43-3"><a href="deduplicación-de-registros.html#cb43-3" tabindex="-1"></a></span>
<span id="cb43-4"><a href="deduplicación-de-registros.html#cb43-4" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;RLdata10000&quot;</span>)</span>
<span id="cb43-5"><a href="deduplicación-de-registros.html#cb43-5" tabindex="-1"></a><span class="fu">head</span>(RLdata10000)</span></code></pre></div>
<pre><code>##   fname_c1 fname_c2   lname_c1 lname_c2   by bm bd
## 1    FRANK     &lt;NA&gt;    MUELLER     &lt;NA&gt; 1967  9 27
## 2   MARTIN     &lt;NA&gt;    SCHWARZ     &lt;NA&gt; 1967  2 17
## 3  HERBERT     &lt;NA&gt; ZIMMERMANN     &lt;NA&gt; 1961 11  6
## 4     HANS     &lt;NA&gt;    SCHMITT     &lt;NA&gt; 1945  8 14
## 5      UWE     &lt;NA&gt;     KELLER     &lt;NA&gt; 2000  7  5
## 6   DANIEL     &lt;NA&gt;   HEINRICH     &lt;NA&gt; 1967  5  6</code></pre>
<p>Al igual que en el ejemplo anterior, suponga que un subconjunto de los datos de la muestra E fue revisado de forma manual para establecer la coincidencia con la muestra P, y que ha conservado un id único que permite realizar el emparejamiento exacto.</p>
<p>En el caso de <code>RLdata10000</code> se cuenta con el vector <code>identity.RLdata10000</code> que conserva el id único de cada registro, esto con fines de entrenamiento de un modelo o como en este caso, para mostrar el uso de los procedimientos. Note que solo hay 9.000 identificadores únicos, por lo que 1.000 son duplicados, el desafío es que los métodos de emparejamiento los identifique con el menor error.</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="deduplicación-de-registros.html#cb45-1" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(identity.RLdata10000))</span></code></pre></div>
<pre><code>## [1] 9000</code></pre>
<p>Se define el vector <code>var</code> con todas las variables que se hará el emparejamiento, en el vector <code>char_vars</code> se conservan las variables de cadena donde es posible hacer cálculos con métricas de similaridad, <code>cal_simil</code> especifica para cuales de las variables de <code>char_vars</code> no se exige coincidencias exactas. La métrica que se usa por defecto es Jaro-Winkler, pero hay otras opciones que se pueden implementar.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="deduplicación-de-registros.html#cb47-1" tabindex="-1"></a>vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;fname_c1&quot;</span>, <span class="st">&quot;lname_c1&quot;</span>, <span class="st">&quot;by&quot;</span>, <span class="st">&quot;bm&quot;</span>, <span class="st">&quot;bd&quot;</span>)</span>
<span id="cb47-2"><a href="deduplicación-de-registros.html#cb47-2" tabindex="-1"></a>char_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;fname_c1&quot;</span>, <span class="st">&quot;lname_c1&quot;</span>)</span>
<span id="cb47-3"><a href="deduplicación-de-registros.html#cb47-3" tabindex="-1"></a>cal_simil <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;fname_c1&quot;</span>, <span class="st">&quot;lname_c1&quot;</span>)</span></code></pre></div>
<p>La función <code>fastLink</code> permite identificar los duplicados usando los mismos datos en los argumentos de los <code>dfA</code> y <code>dfB</code>, y cuenta con un argumento para distribuir en varios cores el procesamiento. <code>cut.a</code> es el umbral mínimo de probabilidad posterior para aceptar un <em>emparejamiento</em> y <code>cut.p</code> es el umbral inferior para considerar un registro como <em>emparejamiento potencial</em> (que pase a revisión clerical), es decir, si la probabilidad está entre <code>cut.p</code> y <code>cut.a</code>, el par se considera un <em>emparejamiento potencial</em> que requiere revisión manual. Si la probabilidad es menor que <code>cut.p</code>, el registro se considera como <em>no emparejado</em>. Se debe tener en cuenta que un valor muy alto de <code>cut.a</code> puede originar más precisión pero menos emparejamientos, pero si <code>cut.a</code> es bajo entonces se espera un mayor <em>recall</em> y un mayor riesgo de falsos positivos.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="deduplicación-de-registros.html#cb48-1" tabindex="-1"></a>nCores <span class="ot">&lt;-</span> <span class="fu">detectCores</span>()</span>
<span id="cb48-2"><a href="deduplicación-de-registros.html#cb48-2" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">fastLink</span>(<span class="at">dfA =</span> RLdata10000, <span class="at">dfB =</span> RLdata10000,</span>
<span id="cb48-3"><a href="deduplicación-de-registros.html#cb48-3" tabindex="-1"></a>                <span class="at">varnames =</span> vars,</span>
<span id="cb48-4"><a href="deduplicación-de-registros.html#cb48-4" tabindex="-1"></a>                <span class="at">stringdist.match =</span> char_vars,</span>
<span id="cb48-5"><a href="deduplicación-de-registros.html#cb48-5" tabindex="-1"></a>                <span class="at">stringdist.method =</span> <span class="st">&quot;jw&quot;</span>,</span>
<span id="cb48-6"><a href="deduplicación-de-registros.html#cb48-6" tabindex="-1"></a>                <span class="at">partial.match =</span> cal_simil,</span>
<span id="cb48-7"><a href="deduplicación-de-registros.html#cb48-7" tabindex="-1"></a>                <span class="at">cut.a =</span> <span class="fl">0.94</span>,</span>
<span id="cb48-8"><a href="deduplicación-de-registros.html#cb48-8" tabindex="-1"></a>                <span class="at">cut.p =</span> <span class="fl">0.84</span>,</span>
<span id="cb48-9"><a href="deduplicación-de-registros.html#cb48-9" tabindex="-1"></a>                <span class="at">dedupe =</span> <span class="cn">FALSE</span>,</span>
<span id="cb48-10"><a href="deduplicación-de-registros.html#cb48-10" tabindex="-1"></a>                <span class="at">n.cores =</span> nCores <span class="sc">-</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## 
## ==================== 
## fastLink(): Fast Probabilistic Record Linkage
## ==================== 
## 
## If you set return.all to FALSE, you will not be able to calculate a confusion table as a summary statistic.
## dfA and dfB are identical, assuming deduplication of a single data set.
## Setting return.all to FALSE.
## 
## Calculating matches for each variable.</code></pre>
<pre><code>## Getting counts for parameter estimation.
##     Parallelizing calculation using OpenMP. 1 threads out of 8 are used.
## Running the EM algorithm.
## Getting the indices of estimated matches.
##     Parallelizing calculation using OpenMP. 1 threads out of 8 are used.
## Calculating the posterior for each pair of matched observations.
## Getting the match patterns for each estimated match.</code></pre>
<p>El procedimiento genera la variable <code>dedupe.ids</code> para todo el conjunto de datos. La función <code>getMatches</code> permite extraer el conjunto de datos con la variable de identificación.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="deduplicación-de-registros.html#cb51-1" tabindex="-1"></a>index_dup <span class="ot">&lt;-</span> <span class="fu">getMatches</span>(<span class="at">dfA =</span> RLdata10000, <span class="at">dfB =</span> RLdata10000, <span class="at">fl.out =</span> res) </span>
<span id="cb51-2"><a href="deduplicación-de-registros.html#cb51-2" tabindex="-1"></a>index_dup <span class="ot">&lt;-</span> index_dup <span class="sc">|&gt;</span> <span class="fu">bind_cols</span>(<span class="fu">data.frame</span>(<span class="at">id =</span> identity.RLdata10000))</span>
<span id="cb51-3"><a href="deduplicación-de-registros.html#cb51-3" tabindex="-1"></a></span>
<span id="cb51-4"><a href="deduplicación-de-registros.html#cb51-4" tabindex="-1"></a>duplicados <span class="ot">&lt;-</span> <span class="fu">get_dupes</span>(index_dup, dedupe.ids)</span>
<span id="cb51-5"><a href="deduplicación-de-registros.html#cb51-5" tabindex="-1"></a><span class="fu">head</span>(duplicados)</span></code></pre></div>
<pre><code>##   dedupe.ids dupe_count fname_c1 fname_c2    lname_c1 lname_c2   by bm bd   id
## 1        420          3 GUENTHER     &lt;NA&gt; ZIMMERMWANN     &lt;NA&gt; 1971  6 23 1794
## 2        420          3 GUENTHER     &lt;NA&gt;  ZIMMERMANN     &lt;NA&gt; 1992  6 23 1864
## 3        420          3 GUENTHER     &lt;NA&gt;  ZIMMERMANN     &lt;NA&gt; 1971  6 23 1794
## 4       3969          3  GERTRUD     &lt;NA&gt;     MUELLER     &lt;NA&gt; 1964  7 27 8970
## 5       3969          3  GERTRUD     &lt;NA&gt;     MUELOER     &lt;NA&gt; 1964  7 11 7616
## 6       3969          3  GERTRUD     &lt;NA&gt;     MUELLER     &lt;NA&gt; 1964  7 11 7616</code></pre>
<p>El desempeño del modelo se puede evaluar mediante una matriz de confusión que compara las predicciones del modelo con los valores reales. En este caso, el modelo identificó correctamente 982 verdaderos positivos, es decir, observaciones que efectivamente eran duplicados. Sin embargo, también generó 18 falsos negativos, que son casos verdaderos que el modelo no logró identificar correctamente. Además, el modelo produjo 63 falsos positivos, es decir, casos que fueron clasificados como verdaderos por el modelo, pero en realidad no eran duplicados.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="deduplicación-de-registros.html#cb53-1" tabindex="-1"></a>ids_duplicados <span class="ot">&lt;-</span> <span class="fu">names</span>(<span class="fu">table</span>(identity.RLdata10000))[<span class="fu">table</span>(identity.RLdata10000) <span class="sc">&gt;</span> <span class="dv">1</span>]</span>
<span id="cb53-2"><a href="deduplicación-de-registros.html#cb53-2" tabindex="-1"></a>todos_ids <span class="ot">&lt;-</span> <span class="fu">union</span>(<span class="fu">unique</span>(duplicados<span class="sc">$</span>id), <span class="fu">unique</span>(ids_duplicados))</span>
<span id="cb53-3"><a href="deduplicación-de-registros.html#cb53-3" tabindex="-1"></a></span>
<span id="cb53-4"><a href="deduplicación-de-registros.html#cb53-4" tabindex="-1"></a>dupes_model <span class="ot">&lt;-</span> todos_ids <span class="sc">%in%</span> <span class="fu">unique</span>(duplicados<span class="sc">$</span>id)</span>
<span id="cb53-5"><a href="deduplicación-de-registros.html#cb53-5" tabindex="-1"></a>dupes_real <span class="ot">&lt;-</span> todos_ids <span class="sc">%in%</span> ids_duplicados</span>
<span id="cb53-6"><a href="deduplicación-de-registros.html#cb53-6" tabindex="-1"></a></span>
<span id="cb53-7"><a href="deduplicación-de-registros.html#cb53-7" tabindex="-1"></a>matriz <span class="ot">&lt;-</span> <span class="fu">table</span>(<span class="at">Real =</span> dupes_real, <span class="at">Modelo =</span> dupes_model)</span>
<span id="cb53-8"><a href="deduplicación-de-registros.html#cb53-8" tabindex="-1"></a><span class="fu">print</span>(matriz)</span></code></pre></div>
<pre><code>##        Modelo
## Real    FALSE TRUE
##   FALSE     0   63
##   TRUE     18  982</code></pre>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="implementación.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="vinculación-de-registros.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/psirusteam/PESguidelines/06-Emparejamiento.rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Encuesta PostCensal.pdf", "Encuesta PostCensal.epub", "Encuesta PostCensal.mobi"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
},
"tconfig": null
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
