<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>6.8 Implementación | Fundamentos estadísticos para el análisis de las encuestas postcensales</title>
  <meta name="description" content="Encuestas Postcensales" />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="6.8 Implementación | Fundamentos estadísticos para el análisis de las encuestas postcensales" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Encuestas Postcensales" />
  <meta name="github-repo" content="psirusteam/PESguidelines" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="6.8 Implementación | Fundamentos estadísticos para el análisis de las encuestas postcensales" />
  
  <meta name="twitter:description" content="Encuestas Postcensales" />
  

<meta name="author" content="Andrés Gutiérrez, Giovany Babativa, Stalyn Guerrero" />


<meta name="date" content="2025-07-09" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="evaluación.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="libs/d3-3.3.8/d3.min.js"></script>
<script src="libs/dagre-0.4.0/dagre-d3.min.js"></script>
<link href="libs/mermaid-0.3.0/dist/mermaid.css" rel="stylesheet" />
<script src="libs/mermaid-0.3.0/dist/mermaid.slim.min.js"></script>
<link href="libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet" />
<script src="libs/chromatography-0.1/chromatography.js"></script>
<script src="libs/DiagrammeR-binding-1.0.11/DiagrammeR.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Encuestas postcensales</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Abstract</a></li>
<li class="chapter" data-level="1" data-path="el-sistema-de-estimación-dual.html"><a href="el-sistema-de-estimación-dual.html"><i class="fa fa-check"></i><b>1</b> El sistema de estimación dual</a>
<ul>
<li class="chapter" data-level="1.1" data-path="planteamiento-del-problema.html"><a href="planteamiento-del-problema.html"><i class="fa fa-check"></i><b>1.1</b> Planteamiento del problema</a></li>
<li class="chapter" data-level="1.2" data-path="condiciones-y-supuestos.html"><a href="condiciones-y-supuestos.html"><i class="fa fa-check"></i><b>1.2</b> Condiciones y supuestos</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="condiciones-y-supuestos.html"><a href="condiciones-y-supuestos.html#estabilidad-poblacional"><i class="fa fa-check"></i><b>1.2.1</b> Estabilidad poblacional</a></li>
<li class="chapter" data-level="1.2.2" data-path="condiciones-y-supuestos.html"><a href="condiciones-y-supuestos.html#sec:multinomial"><i class="fa fa-check"></i><b>1.2.2</b> Estructura multinomial</a></li>
<li class="chapter" data-level="1.2.3" data-path="condiciones-y-supuestos.html"><a href="condiciones-y-supuestos.html#independencia-autónoma"><i class="fa fa-check"></i><b>1.2.3</b> Independencia autónoma</a></li>
<li class="chapter" data-level="1.2.4" data-path="condiciones-y-supuestos.html"><a href="condiciones-y-supuestos.html#independencia-causal"><i class="fa fa-check"></i><b>1.2.4</b> Independencia causal</a></li>
<li class="chapter" data-level="1.2.5" data-path="condiciones-y-supuestos.html"><a href="condiciones-y-supuestos.html#emparejamiento"><i class="fa fa-check"></i><b>1.2.5</b> Emparejamiento</a></li>
<li class="chapter" data-level="1.2.6" data-path="condiciones-y-supuestos.html"><a href="condiciones-y-supuestos.html#eventos-espurios"><i class="fa fa-check"></i><b>1.2.6</b> Eventos espurios</a></li>
<li class="chapter" data-level="1.2.7" data-path="condiciones-y-supuestos.html"><a href="condiciones-y-supuestos.html#postestratificación"><i class="fa fa-check"></i><b>1.2.7</b> Postestratificación</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="inferencia.html"><a href="inferencia.html"><i class="fa fa-check"></i><b>1.3</b> Inferencia</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="inferencia.html"><a href="inferencia.html#los-estimadores-del-sistema-dual"><i class="fa fa-check"></i><b>1.3.1</b> Los estimadores del sistema dual</a></li>
<li class="chapter" data-level="1.3.2" data-path="inferencia.html"><a href="inferencia.html#propiedades-del-estimador"><i class="fa fa-check"></i><b>1.3.2</b> Propiedades del estimador</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="estimación-dual-con-la-muestra-de-la-encuesta.html"><a href="estimación-dual-con-la-muestra-de-la-encuesta.html"><i class="fa fa-check"></i><b>2</b> Estimación dual con la muestra de la encuesta</a>
<ul>
<li class="chapter" data-level="2.1" data-path="el-diseño-de-muestreo.html"><a href="el-diseño-de-muestreo.html"><i class="fa fa-check"></i><b>2.1</b> El diseño de muestreo</a></li>
<li class="chapter" data-level="2.2" data-path="la-muestra-e-y-la-muestra-p.html"><a href="la-muestra-e-y-la-muestra-p.html"><i class="fa fa-check"></i><b>2.2</b> La muestra E y la muestra P</a></li>
<li class="chapter" data-level="2.3" data-path="los-estimadores-de-muestreo.html"><a href="los-estimadores-de-muestreo.html"><i class="fa fa-check"></i><b>2.3</b> Los estimadores de muestreo</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="cap3.html"><a href="cap3.html"><i class="fa fa-check"></i><b>3</b> Enumeraciones y procedimientos</a>
<ul>
<li class="chapter" data-level="3.1" data-path="enumeraciones-correctas-con-la-muestra-e.html"><a href="enumeraciones-correctas-con-la-muestra-e.html"><i class="fa fa-check"></i><b>3.1</b> Enumeraciones correctas con la muestra E</a></li>
<li class="chapter" data-level="3.2" data-path="reconsturcción-de-los-hogares-con-la-muestra-p.html"><a href="reconsturcción-de-los-hogares-con-la-muestra-p.html"><i class="fa fa-check"></i><b>3.2</b> Reconsturcción de los hogares con la muestra P</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="reconsturcción-de-los-hogares-con-la-muestra-p.html"><a href="reconsturcción-de-los-hogares-con-la-muestra-p.html#procedimiento-a"><i class="fa fa-check"></i><b>3.2.1</b> Procedimiento A</a></li>
<li class="chapter" data-level="3.2.2" data-path="reconsturcción-de-los-hogares-con-la-muestra-p.html"><a href="reconsturcción-de-los-hogares-con-la-muestra-p.html#procedimiento-b"><i class="fa fa-check"></i><b>3.2.2</b> Procedimiento B</a></li>
<li class="chapter" data-level="3.2.3" data-path="reconsturcción-de-los-hogares-con-la-muestra-p.html"><a href="reconsturcción-de-los-hogares-con-la-muestra-p.html#procedimiento-c"><i class="fa fa-check"></i><b>3.2.3</b> Procedimiento C</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="estimadores-del-sistema-dual.html"><a href="estimadores-del-sistema-dual.html"><i class="fa fa-check"></i><b>4</b> Estimadores del sistema dual</a>
<ul>
<li class="chapter" data-level="4.1" data-path="estimador-de-petersen.html"><a href="estimador-de-petersen.html"><i class="fa fa-check"></i><b>4.1</b> Estimador de Petersen</a></li>
<li class="chapter" data-level="4.2" data-path="estimador-de-chapman.html"><a href="estimador-de-chapman.html"><i class="fa fa-check"></i><b>4.2</b> Estimador de Chapman</a></li>
<li class="chapter" data-level="4.3" data-path="estimador-de-nour.html"><a href="estimador-de-nour.html"><i class="fa fa-check"></i><b>4.3</b> Estimador de Nour</a></li>
<li class="chapter" data-level="4.4" data-path="estimador-de-chao.html"><a href="estimador-de-chao.html"><i class="fa fa-check"></i><b>4.4</b> Estimador de Chao</a></li>
<li class="chapter" data-level="4.5" data-path="estimador-de-webster-kemp.html"><a href="estimador-de-webster-kemp.html"><i class="fa fa-check"></i><b>4.5</b> Estimador de Webster-Kemp</a></li>
<li class="chapter" data-level="4.6" data-path="estimador-de-zelterman.html"><a href="estimador-de-zelterman.html"><i class="fa fa-check"></i><b>4.6</b> Estimador de Zelterman</a></li>
<li class="chapter" data-level="4.7" data-path="modelos-log-lineales.html"><a href="modelos-log-lineales.html"><i class="fa fa-check"></i><b>4.7</b> Modelos log-lineales</a></li>
<li class="chapter" data-level="4.8" data-path="otros-modelos.html"><a href="otros-modelos.html"><i class="fa fa-check"></i><b>4.8</b> Otros modelos</a></li>
<li class="chapter" data-level="4.9" data-path="notas-adicionales.html"><a href="notas-adicionales.html"><i class="fa fa-check"></i><b>4.9</b> Notas adicionales</a></li>
<li class="chapter" data-level="4.10" data-path="cuadro-comparativo-de-los-estimadores.html"><a href="cuadro-comparativo-de-los-estimadores.html"><i class="fa fa-check"></i><b>4.10</b> Cuadro comparativo de los estimadores</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="evaluación-de-la-cobertura-censal.html"><a href="evaluación-de-la-cobertura-censal.html"><i class="fa fa-check"></i><b>5</b> Evaluación de la cobertura censal</a>
<ul>
<li class="chapter" data-level="5.1" data-path="objetivos-de-la-encuesta-de-cobertura.html"><a href="objetivos-de-la-encuesta-de-cobertura.html"><i class="fa fa-check"></i><b>5.1</b> Objetivos de la encuesta de cobertura</a></li>
<li class="chapter" data-level="5.2" data-path="componentes-de-la-cobertura-censal.html"><a href="componentes-de-la-cobertura-censal.html"><i class="fa fa-check"></i><b>5.2</b> Componentes de la cobertura censal</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="componentes-de-la-cobertura-censal.html"><a href="componentes-de-la-cobertura-censal.html#enumeraciones-correctas"><i class="fa fa-check"></i><b>5.2.1</b> Enumeraciones correctas</a></li>
<li class="chapter" data-level="5.2.2" data-path="componentes-de-la-cobertura-censal.html"><a href="componentes-de-la-cobertura-censal.html#enumeraciones-erróneas"><i class="fa fa-check"></i><b>5.2.2</b> Enumeraciones erróneas</a></li>
<li class="chapter" data-level="5.2.3" data-path="componentes-de-la-cobertura-censal.html"><a href="componentes-de-la-cobertura-censal.html#omisiones"><i class="fa fa-check"></i><b>5.2.3</b> Omisiones</a></li>
<li class="chapter" data-level="5.2.4" data-path="componentes-de-la-cobertura-censal.html"><a href="componentes-de-la-cobertura-censal.html#imputación"><i class="fa fa-check"></i><b>5.2.4</b> Imputación</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="protocolo-de-clasificación.html"><a href="protocolo-de-clasificación.html"><i class="fa fa-check"></i><b>5.3</b> Protocolo de clasificación</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="protocolo-de-clasificación.html"><a href="protocolo-de-clasificación.html#preprocesamiento-de-datos"><i class="fa fa-check"></i><b>5.3.1</b> Preprocesamiento de datos</a></li>
<li class="chapter" data-level="5.3.2" data-path="protocolo-de-clasificación.html"><a href="protocolo-de-clasificación.html#emparejamiento-de-registros"><i class="fa fa-check"></i><b>5.3.2</b> Emparejamiento de registros</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="flujo-general-del-procedimiento.html"><a href="flujo-general-del-procedimiento.html"><i class="fa fa-check"></i><b>5.4</b> Flujo general del procedimiento</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="proceso-de-emparejamiento-probabilístico.html"><a href="proceso-de-emparejamiento-probabilístico.html"><i class="fa fa-check"></i><b>6</b> Proceso de emparejamiento probabilístico</a>
<ul>
<li class="chapter" data-level="6.1" data-path="geolocalización.html"><a href="geolocalización.html"><i class="fa fa-check"></i><b>6.1</b> Geolocalización</a></li>
<li class="chapter" data-level="6.2" data-path="flujo-general.html"><a href="flujo-general.html"><i class="fa fa-check"></i><b>6.2</b> Flujo general</a></li>
<li class="chapter" data-level="6.3" data-path="preprocesamiento.html"><a href="preprocesamiento.html"><i class="fa fa-check"></i><b>6.3</b> Preprocesamiento</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="preprocesamiento.html"><a href="preprocesamiento.html#limpieza-de-los-datos"><i class="fa fa-check"></i><b>6.3.1</b> Limpieza de los datos</a></li>
<li class="chapter" data-level="6.3.2" data-path="preprocesamiento.html"><a href="preprocesamiento.html#codificación-fonética"><i class="fa fa-check"></i><b>6.3.2</b> Codificación fonética</a></li>
<li class="chapter" data-level="6.3.3" data-path="preprocesamiento.html"><a href="preprocesamiento.html#metaphone"><i class="fa fa-check"></i><b>6.3.3</b> Metaphone</a></li>
<li class="chapter" data-level="6.3.4" data-path="preprocesamiento.html"><a href="preprocesamiento.html#algoritmo-statistics-canada"><i class="fa fa-check"></i><b>6.3.4</b> Algoritmo Statistics Canada</a></li>
<li class="chapter" data-level="6.3.5" data-path="preprocesamiento.html"><a href="preprocesamiento.html#adaptación-para-encuestas-de-américa-latina"><i class="fa fa-check"></i><b>6.3.5</b> Adaptación para Encuestas de América Latina</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="indexación.html"><a href="indexación.html"><i class="fa fa-check"></i><b>6.4</b> Indexación</a></li>
<li class="chapter" data-level="6.5" data-path="comparación.html"><a href="comparación.html"><i class="fa fa-check"></i><b>6.5</b> Comparación</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="comparación.html"><a href="comparación.html#distancia-de-levenshtein"><i class="fa fa-check"></i><b>6.5.1</b> Distancia de Levenshtein</a></li>
<li class="chapter" data-level="6.5.2" data-path="comparación.html"><a href="comparación.html#comparación-de-jaro-y-winkler"><i class="fa fa-check"></i><b>6.5.2</b> Comparación de Jaro y Winkler</a></li>
<li class="chapter" data-level="6.5.3" data-path="comparación.html"><a href="comparación.html#comparación-de-fechas-y-edades"><i class="fa fa-check"></i><b>6.5.3</b> Comparación de fechas y edades</a></li>
<li class="chapter" data-level="6.5.4" data-path="comparación.html"><a href="comparación.html#comparación-geográfica"><i class="fa fa-check"></i><b>6.5.4</b> Comparación geográfica</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="clasificación.html"><a href="clasificación.html"><i class="fa fa-check"></i><b>6.6</b> Clasificación</a></li>
<li class="chapter" data-level="6.7" data-path="evaluación.html"><a href="evaluación.html"><i class="fa fa-check"></i><b>6.7</b> Evaluación</a>
<ul>
<li class="chapter" data-level="6.7.1" data-path="evaluación.html"><a href="evaluación.html#métricas-de-desempeño"><i class="fa fa-check"></i><b>6.7.1</b> Métricas de desempeño</a></li>
<li class="chapter" data-level="6.7.2" data-path="evaluación.html"><a href="evaluación.html#métricas-de-eficiencia"><i class="fa fa-check"></i><b>6.7.2</b> Métricas de eficiencia</a></li>
<li class="chapter" data-level="6.7.3" data-path="evaluación.html"><a href="evaluación.html#revisión-clerical"><i class="fa fa-check"></i><b>6.7.3</b> Revisión clerical</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="implementación.html"><a href="implementación.html"><i class="fa fa-check"></i><b>6.8</b> Implementación</a>
<ul>
<li class="chapter" data-level="6.8.1" data-path="implementación.html"><a href="implementación.html#deduplicación-de-registros"><i class="fa fa-check"></i><b>6.8.1</b> Deduplicación de registros</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a Encuestas postcensales </a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Fundamentos estadísticos para el análisis de las encuestas postcensales</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="implementación" class="section level2 hasAnchor" number="6.8">
<h2><span class="header-section-number">6.8</span> Implementación<a href="implementación.html#implementación" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A continuación se presenta un resumen de los principales paquetes de R y Python que se pueden utilizar para la vinculación probabilística de registros:</p>
<table>
<colgroup>
<col width="7%" />
<col width="12%" />
<col width="80%" />
</colgroup>
<thead>
<tr class="header">
<th>Lenguaje</th>
<th>Paquete</th>
<th>Características principales</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>R</td>
<td><code>RecordLinkage</code></td>
<td>Implementa Fellegi-Sunter, Soundex, Jaro-Winkler, Levenshtein. Permite bloques, clasificación supervisada o no.</td>
</tr>
<tr class="even">
<td>R</td>
<td><code>fastLink</code></td>
<td>Modelo bayesiano de Fellegi-Sunter. Maneja datos faltantes. Permite estimación de probabilidades y escalabilidad.</td>
</tr>
<tr class="odd">
<td>R</td>
<td><code>fuzzyjoin</code></td>
<td>Permite uniones por coincidencias parciales como <code>stringdist</code>, <code>regex</code> y se integra con <code>dplyr</code>.</td>
</tr>
<tr class="even">
<td>R</td>
<td><code>stringdist</code></td>
<td>Ofrece múltiples métricas de distancia (Levenshtein, Jaccard, Jaro, Hamming). Útil para comparaciones de texto.</td>
</tr>
<tr class="odd">
<td>Python</td>
<td><code>recordlinkage</code></td>
<td>Implementa Fellegi-Sunter, SVM, Random Forests. Permite bloques y evaluación de desempeño.</td>
</tr>
<tr class="even">
<td>Python</td>
<td><code>Dedupe</code></td>
<td>Usa aprendizaje supervisado y semi-supervisado. Permite bloques y métodos de clúster.</td>
</tr>
<tr class="odd">
<td>Python</td>
<td><code>splink</code></td>
<td>Basado en Fellegi-Sunter, escalable con Spark, DuckDB o SQL. Visualización interactiva. Soporta paralelización.</td>
</tr>
</tbody>
</table>
<div id="deduplicación-de-registros" class="section level3 hasAnchor" number="6.8.1">
<h3><span class="header-section-number">6.8.1</span> Deduplicación de registros<a href="implementación.html#deduplicación-de-registros" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Una etapa clave en el cálculo de la omisión censal, es asegurar que la base de enumeración de la encuesta de cobertura no tiene duplicados. Poder identificar si una persona ha sido enumerada más de una vez en el censo, se conoce como proceso de deduplicación.</p>
<p>Para ilustrar este procedimiento se implementará un análisis supervisado utilizando los datos simulados <code>RLdata500</code> incluidos en el paquete <code>RecordLinkage</code>. El conjunto de datos contiene 500 registros simulados, incluyendo nombres, apellidos, fechas de nacimiento y un identificador de la persona real (<code>identity.RLdata500</code>). Suponga que este es un conjunto de entrenamiento que fue seleccionado con unos registros del censo, y en el cual se realizó un proceso de identificación y revisión clerical para identificar con certeza si un registro es duplicado o no, de esta manera es posible entrenar un modelo, realizar evaluaciones de precisión y entender mejor las decisiones del algoritmo.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="implementación.html#cb22-1" tabindex="-1"></a><span class="fu">library</span>(RecordLinkage)</span>
<span id="cb22-2"><a href="implementación.html#cb22-2" tabindex="-1"></a><span class="fu">data</span>(RLdata500)</span>
<span id="cb22-3"><a href="implementación.html#cb22-3" tabindex="-1"></a><span class="fu">head</span>(RLdata500)</span></code></pre></div>
<pre><code>##   fname_c1 fname_c2 lname_c1 lname_c2   by bm bd
## 1  CARSTEN     &lt;NA&gt;    MEIER     &lt;NA&gt; 1949  7 22
## 2     GERD     &lt;NA&gt;    BAUER     &lt;NA&gt; 1968  7 27
## 3   ROBERT     &lt;NA&gt; HARTMANN     &lt;NA&gt; 1930  4 30
## 4   STEFAN     &lt;NA&gt;    WOLFF     &lt;NA&gt; 1957  9  2
## 5     RALF     &lt;NA&gt;  KRUEGER     &lt;NA&gt; 1966  1 13
## 6  JUERGEN     &lt;NA&gt;   FRANKE     &lt;NA&gt; 1929  7  4</code></pre>
<p>En caso de realizar todas la comparaciones por pares, serían necesarias 124.750 comparaciones:</p>
<p><span class="math display">\[\binom{500}{2} = 124.750\]</span>
Lo anterior es manejable en conjuntos de datos pequeños, pero en los casos de censos o encuestas de cobertura no resulta viable aplicar el total de comparaciones, por lo que será necesario realizar una indexación con unos bloques de comparación.</p>
<p>Como se ha mencionado antes, el bloqueo consiste en agrupar los registros en bloques más pequeños usando una o más variables, de manera que solo se comparan registros dentro del mismo bloque. En este ejemplo se usará la primera letra del apellido como clave de bloqueo.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="implementación.html#cb24-1" tabindex="-1"></a>inic_apell <span class="ot">&lt;-</span> <span class="fu">substr</span>(RLdata500[,<span class="st">&quot;lname_c1&quot;</span>], <span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb24-2"><a href="implementación.html#cb24-2" tabindex="-1"></a>(tbl <span class="ot">&lt;-</span> <span class="fu">table</span>(inic_apell))</span></code></pre></div>
<pre><code>## inic_apell
##   A   B   D   E   F   G   H   J   K   L   M   N   O   P   R   S   T   V   W   Z 
##   5  56   2   6  38  12  32   8  46  13  76   8   4   6   7 115   2   7  52   5</code></pre>
<p>Lo anterior genera 20 bloques, donde el número de registros por bloque puede ser diferente. Como ahora el número de comparaciones se realiza dentro de cada bloque, esto reduce drásticamente el número total de comparaciones que se tienen que realizar. Sin embargo, es recomendable evitar una alta variación en el número de registros por bloque, esto debido a que algunos bloques con un alto número de registros puede incremetar fuertemente el costo computacional. En este caso el número de registros por bloque varía entre 2 y 115.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="implementación.html#cb26-1" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">as.numeric</span>(<span class="fu">table</span>(inic_apell)))</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    2.00    5.75    8.00   25.00   40.00  115.00</code></pre>
<p>A pesar de lo anterior, el número de pares posibles tras aplicar el bloqueo baja de 124750 a 14805 pares. Esta reducción es crucial para el rendimiento computacional del algoritmo. A continuación se observa el número de comparaciones por bloque.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="implementación.html#cb28-1" tabindex="-1"></a><span class="fu">sapply</span>(tbl, choose, <span class="at">k=</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>##    A    B    D    E    F    G    H    J    K    L    M    N    O    P    R    S 
##   10 1540    1   15  703   66  496   28 1035   78 2850   28    6   15   21 6555 
##    T    V    W    Z 
##    1   21 1326   10</code></pre>
<p>Para entrenar el modelo, se agrega a la tabla de datos el id de cada persona y se quita la información redundante:</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="implementación.html#cb30-1" tabindex="-1"></a>RLdata500c <span class="ot">&lt;-</span> RLdata500 <span class="sc">|&gt;</span>  </span>
<span id="cb30-2"><a href="implementación.html#cb30-2" tabindex="-1"></a>              <span class="fu">mutate</span>(<span class="at">id =</span> identity.RLdata500) <span class="sc">|&gt;</span> </span>
<span id="cb30-3"><a href="implementación.html#cb30-3" tabindex="-1"></a>              <span class="fu">select</span>(<span class="sc">-</span>fname_c2, <span class="sc">-</span>lname_c2)</span></code></pre></div>
<p>Ahora es sencillo filtrar los duplicados reales, esto permite examinar cómo se presentan las inconsistencias reales en los datos y elegir los métodos más apropiados en el entrenamiento del modelo.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="implementación.html#cb31-1" tabindex="-1"></a>dup_set <span class="ot">&lt;-</span> RLdata500c <span class="sc">|&gt;</span> </span>
<span id="cb31-2"><a href="implementación.html#cb31-2" tabindex="-1"></a>           <span class="fu">group_by</span>(id) <span class="sc">|&gt;</span> </span>
<span id="cb31-3"><a href="implementación.html#cb31-3" tabindex="-1"></a>           <span class="fu">filter</span>(<span class="fu">n</span>() <span class="sc">&gt;</span> <span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb31-4"><a href="implementación.html#cb31-4" tabindex="-1"></a>           <span class="fu">ungroup</span>() <span class="sc">|&gt;</span> </span>
<span id="cb31-5"><a href="implementación.html#cb31-5" tabindex="-1"></a>           <span class="fu">arrange</span>(id)</span>
<span id="cb31-6"><a href="implementación.html#cb31-6" tabindex="-1"></a></span>
<span id="cb31-7"><a href="implementación.html#cb31-7" tabindex="-1"></a><span class="fu">tail</span>(dup_set)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 6
##   fname_c1  lname_c1    by    bm    bd    id
##   &lt;chr&gt;     &lt;chr&gt;    &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;dbl&gt;
## 1 RENATE    SCHUTE    1940    12    29   436
## 2 RENATE    SCHULTE   1940    12    29   436
## 3 CHRISTINE PETERS    1993     2     5   442
## 4 CHRISTINE PETERS    1993     2     6   442
## 5 CHRISTA   SCHWARZ   1965     7    13   444
## 6 CHRISTAH  SCHWARZ   1965     7    13   444</code></pre>
<p>Al calcular la distancia de Levenshtein observamos que la similaridad aún está lejana de 1, mientras que la métrica de Jaro y Winkler produce un mejor resultado de la similaridad.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="implementación.html#cb33-1" tabindex="-1"></a><span class="fu">levenshteinSim</span>(<span class="fu">c</span>(<span class="st">&quot;SCHUTE&quot;</span>, <span class="st">&quot;SCHULTE&quot;</span>),</span>
<span id="cb33-2"><a href="implementación.html#cb33-2" tabindex="-1"></a>               <span class="fu">c</span>(<span class="st">&quot;CHRISTA&quot;</span>, <span class="st">&quot;CHRISTAH&quot;</span>))</span></code></pre></div>
<pre><code>## [1] 0.2857143 0.2500000</code></pre>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="implementación.html#cb35-1" tabindex="-1"></a><span class="fu">jarowinkler</span>(<span class="fu">c</span>(<span class="st">&quot;SCHUTE&quot;</span>, <span class="st">&quot;CHRISTA&quot;</span>),</span>
<span id="cb35-2"><a href="implementación.html#cb35-2" tabindex="-1"></a>            <span class="fu">c</span>(<span class="st">&quot;SCHULTE&quot;</span>, <span class="st">&quot;CHRISTAH&quot;</span>))</span></code></pre></div>
<pre><code>## [1] 0.9714286 0.9750000</code></pre>
<p>El algoritmo de Jaro-Winkler tiende a funcionar mejor cuando los errores son de tipeo o diferencias leves. También se puede aplicar codificación fonética como <code>soundex()</code> o cualquiera de las presentadas en este capítulo.</p>
<p>En el siguiente paso se realiza la comparación de pares con bloqueo supervisado, toda vez que el resultado que identifica si es un duplicado o no es observado. La función <code>compare.dedup()</code> crea un objeto con la comparación entre pares de registros dentro de cada bloque. En este ejemplo se generan pares comparables según los bloques definidos por la primera letra del nombre y año de nacimiento (posiciones 1 y 3). Cada par se compara por igualdad de campos y similitud textual cuando se especifica.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="implementación.html#cb37-1" tabindex="-1"></a>entrenamiento <span class="ot">&lt;-</span> <span class="fu">compare.dedup</span>(RLdata500c[,<span class="sc">-</span><span class="dv">6</span>], </span>
<span id="cb37-2"><a href="implementación.html#cb37-2" tabindex="-1"></a>                               <span class="at">blockfld =</span> <span class="fu">list</span>(<span class="dv">1</span>, <span class="dv">3</span>),  </span>
<span id="cb37-3"><a href="implementación.html#cb37-3" tabindex="-1"></a>                               <span class="at">identity =</span> identity.RLdata500)</span></code></pre></div>
<p>Ahora se calculan pesos probabilísticos para cada par comparado. Este paso estima la probabilidad de que cada par sea un match verdadero, usando un modelo probabilístico basado en la teoría de Fellegi-Sunter.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="implementación.html#cb38-1" tabindex="-1"></a>prob <span class="ot">&lt;-</span> <span class="fu">epiWeights</span>(entrenamiento)</span></code></pre></div>
<p>A partir de las probabilidades se clasifica automáticamente los pares en tres categorías:</p>
<ul>
<li><strong>P</strong>: Positivo (match verdadero).</li>
<li><strong>N</strong>: Negativo (no match).</li>
<li><strong>L</strong>: Incertidumbre (requiere revisión clerical).</li>
</ul>
<p>En este caso se especifica un umbral de 0.7, es decir, los pares con probabilidad superior a ese valor se clasifican como positivos.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="implementación.html#cb39-1" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">epiClassify</span>(prob, <span class="fl">0.7</span>)</span>
<span id="cb39-2"><a href="implementación.html#cb39-2" tabindex="-1"></a><span class="fu">summary</span>(res)</span></code></pre></div>
<pre><code>## 
## Deduplication Data Set
## 
## 500 records 
## 2709 record pairs 
## 
## 50 matches
## 2659 non-matches
## 0 pairs with unknown status
## 
## 
## Weight distribution:
## 
## [0.2,0.25] (0.25,0.3] (0.3,0.35] (0.35,0.4] (0.4,0.45] (0.45,0.5] (0.5,0.55] 
##       2318          0        114        131         30         50          8 
## (0.55,0.6] (0.6,0.65] (0.65,0.7] (0.7,0.75] (0.75,0.8] (0.8,0.85] (0.85,0.9] 
##          2         10          0          0         35          8          3 
## 
## 46 links detected 
## 0 possible links detected 
## 2663 non-links detected 
## 
## alpha error: 0.080000
## beta error: 0.000000
## accuracy: 0.998523
## 
## 
## Classification table:
## 
##            classification
## true status    N    P    L
##       FALSE 2659    0    0
##       TRUE     4    0   46</code></pre>
<p>Se observa que la gran mayoría de los pares comparados presentan baja evidencia de coincidencia, con 2318 pares concentrados en el intervalo de peso [0.2, 0.25]. Por otra parte, solo 46 pares alcanzan un peso mayor a 0.7, lo que sugiere una alta probabilidad de ser duplicados.</p>
<p>Según la matriz de clasificación, de los 50 pares realmente duplicados, el modelo identificó correctamente a 46, mientras que 4 no fueron detectados, lo que corresponde a una tasa de falsos negativos de <span class="math inline">\(\alpha = 8\)</span>%. Por otro lado, la tasa de falsos positivos es cero, ya que ningún par no duplicado fue clasificado erróneamente como duplicado.</p>
<p>En conjunto, el modelo alcanzó una exactitud del 99.85%, lo que indica un alto rendimiento en la tarea de deduplicación.</p>
<p>Una vez se ha entrenado el modelo, se puede aplicar una comparación difusa (fuzzy) a todos los datos, para ampliar las posibilidades del ejemplo se usará con la métrica de Jaro-Winkler para todas las variables de cadena (<code>strcmp = TRUE</code>). Se omite el uso de funciones fonéticas (<code>phonetic = FALSE</code>), lo cual es útil cuando queremos detectar errores ortográficos leves y los bloques se arman solo por año de nacimiento. Aunque en la práctica se debe especificar el modelo entrenado.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="implementación.html#cb41-1" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">compare.dedup</span>(RLdata500c[,<span class="sc">-</span><span class="dv">6</span>],</span>
<span id="cb41-2"><a href="implementación.html#cb41-2" tabindex="-1"></a>                        <span class="at">phonetic =</span> <span class="cn">FALSE</span>,</span>
<span id="cb41-3"><a href="implementación.html#cb41-3" tabindex="-1"></a>                        <span class="at">blockfld =</span> <span class="fu">list</span>(<span class="dv">1</span>, <span class="dv">3</span>),</span>
<span id="cb41-4"><a href="implementación.html#cb41-4" tabindex="-1"></a>                        <span class="at">strcmp =</span> <span class="cn">TRUE</span>,</span>
<span id="cb41-5"><a href="implementación.html#cb41-5" tabindex="-1"></a>                        <span class="at">strcmpfun =</span> jarowinkler)</span></code></pre></div>
<p>En conclusión, el uso de bloqueo combinado con comparaciones textuales permite reducir significativamente el esfuerzo computacional, en este caso, más del 90%, al evitar comparaciones innecesarias entre todos los registros. Además, este enfoque es efectivo para detectar duplicados incluso cuando existen errores de tipeo o inconsistencias en los datos, logrando una clasificación precisa de los pares potencialmente duplicados.</p>
<p>Se recomienda ajustar adecuadamente el argumento blockfld para optimizar la eficiencia del proceso, y seleccionar el método de comparación textual (por ejemplo, Jaro-Winkler o Levenshtein) de acuerdo con la calidad y naturaleza de los nombres en los datos.</p>
<p>Finalmente, es importante validar los resultados obtenidos, ya sea mediante revisión manual o a través de reglas adicionales de negocio, para asegurar la confiabilidad del proceso de deduplicación.</p>

<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0">
<div class="csl-entry">
Baillargeon, Sophie, and Louis-Paul Rivest. 2007. <span>“Rcapture: Loglinear Models for Capture-Recapture in r.”</span> <em>Journal of Statistical Software</em> 19: 1–31.
</div>
<div class="csl-entry">
Biemer, Paul P, and Lars E Lyberg. 2003. <em>Introduction to Survey Quality</em>. John Wiley &amp; Sons.
</div>
<div class="csl-entry">
Binder, David A. 2011. <span>“Estimating Model Parameters from a Complex Survey Under a Model-Design Randomization Framework.”</span> <em>Pakistan Journal of Statistics</em> 27 (4): 371–90.
</div>
<div class="csl-entry">
Bishop, Yvonne M, Stephen E Fienberg, and Paul W Holland. 2007. <em>Discrete Multivariate Analysis: Theory and Practice</em>. Springer Science &amp; Business Media.
</div>
<div class="csl-entry">
Bleiholder, Jens, and Felix Naumann. 2009. <span>“Data Fusion.”</span> <em>ACM Computing Surveys (CSUR)</em> 41 (1): 1–41.
</div>
<div class="csl-entry">
Brittain, Sarah, and Dankmar Böhning. 2009. <span>“Estimators in Capture–Recapture Studies with Two Sources.”</span> <em>AStA Advances in Statistical Analysis</em> 93 (1): 23–47.
</div>
<div class="csl-entry">
Bureau, US Census. 2022. <span>“2020 Post-Enumeration Survey Estimation Design.”</span>
</div>
<div class="csl-entry">
Cambon, Jesse, Diego Hernangómez, Christopher Belanger, and Daniel Possenriede. 2021. <span>“Tidygeocoder: An r Package for Geocoding.”</span> <em>Journal of Open Source Software</em> 6 (65): 3544. <a href="https://doi.org/10.21105/joss.03544">https://doi.org/10.21105/joss.03544</a>.
</div>
<div class="csl-entry">
Casella, George, and Roger L. Berger. 2002. <em>Statistical Inference</em>. 2nd ed. Duxbury Press.
</div>
<div class="csl-entry">
CEPAL. 2023. <em>Diseño y Análisis Estadístico de Las Encuestas de Hogares de América Latina</em>. Metodologías de La CEPAL.
</div>
<div class="csl-entry">
Chao, Anne. 1987. <span>“Estimating the Population Size for Capture-Recapture Data with Unequal Catchability.”</span> <em>Biometrics</em>, 783–91.
</div>
<div class="csl-entry">
———. 1989. <span>“Estimating Population Size for Sparse Data in Capture-Recapture Experiments.”</span> <em>Biometrics</em>, 427–38.
</div>
<div class="csl-entry">
Chapman, Douglas George. 1951. <span>“Some Properties of the Hypergeometric Distribution with Applications to Zoological Censuses.”</span> <em>Univ. Calif. Stat.</em> 1: 60–131.
</div>
<div class="csl-entry">
Christen, Peter. 2012. <em>Data Matching Concepts and Techniques for Record Linkage, Entity Resolution, and Duplicate Detection</em>. Springer.
</div>
<div class="csl-entry">
Christen, Victor, Tim Häntschel, Peter Christen, and Erhard Rahm. 2023. <span>“Privacy-Preserving Record Linkage Using Autoencoders.”</span> <em>International Journal of Data Science and Analytics</em> 15 (4): 347–57.
</div>
<div class="csl-entry">
Churches, Tim, Peter Christen, Kim Lim, and Justin Xi Zhu. 2002. <span>“Preparation of Name and Address Data for Record Linkage Using Hidden Markov Models.”</span> <em>BMC Medical Informatics and Decision Making</em> 2: 1–16.
</div>
<div class="csl-entry">
Cormack, Richard M. 1989. <span>“Log-Linear Models for Capture-Recapture.”</span> <em>Biometrics</em>, 395–413.
</div>
<div class="csl-entry">
Dunn, H. L. 1946. <span>“Record Linkage.”</span> <em>American Journal of Public Health and the Nations Health</em> 36 (12): 1412–16. <a href="https://doi.org/10.2105/AJPH.36.12.1412">https://doi.org/10.2105/AJPH.36.12.1412</a>.
</div>
<div class="csl-entry">
Fellegi, Ivan P, and Alan B Sunter. 1969. <span>“A Theory for Record Linkage.”</span> <em>Journal of the American Statistical Association</em> 64 (328): 1183–1210.
</div>
<div class="csl-entry">
Fienberg, Stephen E. 1972. <span>“The Multiple Recapture Census for Closed Populations and Incomplete 2k Contingency Tables.”</span> <em>Biometrika</em> 59 (3): 591–603.
</div>
<div class="csl-entry">
Gutiérrez, Hugo Andrés. 2016. <em>Estrategias de Muestreo: Diseño de Encuestas y Estimación de Parámetros</em>. Segunda edición. Ediciones de la U.
</div>
<div class="csl-entry">
Herzog, Thomas N, Fritz J Scheuren, and William E Winkler. 2007. <em>Data Quality and Record Linkage Techniques</em>. Vol. 1. Springer.
</div>
<div class="csl-entry">
Hogan, Howard. 2003. <span>“The Accuracy and Coverage Evaluation: Theory and Design.”</span> <em>Survey Methodology</em> 29 (2): 129–38. <a href="https://www150.statcan.gc.ca/n1/en/catalogue/12-001-X20030026444">https://www150.statcan.gc.ca/n1/en/catalogue/12-001-X20030026444</a>.
</div>
<div class="csl-entry">
Howard, James P et al. 2020. <span>“Phonetic Spelling Algorithm Implementations for r.”</span> <em>Journal of Statistical Software</em> 95: 1–21.
</div>
<div class="csl-entry">
Larsen, Michael D, and Donald B Rubin. 2001. <span>“Iterative Automated Record Linkage Using Mixture Models.”</span> <em>Journal of the American Statistical Association</em> 96 (453): 32–41.
</div>
<div class="csl-entry">
Lincoln, F. C. 1930. <span>“Calculating Waterfowl Abundance on the Basis of Banding Returns.”</span> <em>Circular</em> 118: 1–4.
</div>
<div class="csl-entry">
Lynch, Billy T, William L Arends, et al. 1977. <span>“Selection of a Surname Coding Procedure for the SRS Record Linkage System.”</span> <em>Washington, DC: US Department of Agriculture, Sample Survey Research Branch, Research Division</em>.
</div>
<div class="csl-entry">
Menestrina, David, Steven Euijong Whang, and Hector Garcia-Molina. 2010. <span>“Evaluating Entity Resolution Results.”</span> <em>Proceedings of the VLDB Endowment</em> 3 (1-2): 208–19.
</div>
<div class="csl-entry">
Nations, United. 2010. <em>Post Enumeration Surveys - Operational Guidelines</em>. 2010 World Population and Housing Census Programme.
</div>
<div class="csl-entry">
Nauman, Felix, and Melanie Herschel. 2022. <em>An Introduction to Duplicate Detection</em>. Springer Nature.
</div>
<div class="csl-entry">
Navarro, Gonzalo. 2001. <span>“A Guided Tour to Approximate String Matching.”</span> <em>ACM Computing Surveys (CSUR)</em> 33 (1): 31–88.
</div>
<div class="csl-entry">
Newcombe, H. B., J. M. Kennedy, S. J. Axford, and A. P. James. 1959. <span>“Automatic Linkage of Vital Records: Computers Can Be Used to Extract" Follow-up" Statistics of Families from Files of Routine Records.”</span> <em>Science</em> 130 (3381): 954–59. <a href="https://doi.org/10.1126/science.130.3381.954">https://doi.org/10.1126/science.130.3381.954</a>.
</div>
<div class="csl-entry">
Newcombe, Howard B., and J. Michael Kennedy. 1962. <span>“Record Linkage: Making Maximum Use of the Discriminating Power of Identifying Information.”</span> <em>Communications of the ACM</em> 5 (11): 563–66. <a href="https://doi.org/10.1145/368996.369032">https://doi.org/10.1145/368996.369032</a>.
</div>
<div class="csl-entry">
Nour, El-Sayed. 1982. <span>“On the Estimation of the Total Number of Vital Events with Data from Dual Collection Systems.”</span> <em>Journal of the Royal Statistical Society Series A: Statistics in Society</em> 145 (1): 106–16.
</div>
<div class="csl-entry">
Odell, Margaret, and Robert Russell. 1918. <span>“The Soundex Coding System.”</span> <em>US Patents</em> 1261167: 9.
</div>
<div class="csl-entry">
Petersen, Carl G. J. 1896. <span>“The Yearly Immigration of Young Plaice into the Limfjord from the German Sea.”</span> <em>Report of the Danish Biological Station</em> 6: 1–48.
</div>
<div class="csl-entry">
Philips, Lawrence. 1990. <span>“Hanging on the Metaphone.”</span> <em>Computer Language</em> 7 (12): 39–43.
</div>
<div class="csl-entry">
Rivest, Louis-Paul, and Sophie Baillargeon. 2014. <span>“Capture-Recapture Methods for Estimating the Size of a Population: Dealing with Variable Capture Probabilities.”</span> <em>Statistics in Action: A Canadian Outlook</em> 40: 289–304.
</div>
<div class="csl-entry">
Sadinle, Mauricio. 2009. <span>“Transformed Logit Confidence Intervals for Small Populations in Single Capture–Recapture Estimation.”</span> <em>Communications in Statistics-Simulation and Computation</em> 38 (9): 1909–24.
</div>
<div class="csl-entry">
Schnabel, Z. E. 1938. <span>“The Estimation of the Total Fish Population of a Lake.”</span> <em>American Mathematical Monthly</em> 45: 348–52.
</div>
<div class="csl-entry">
Seber, George Arthur Frederick. 1982. <em>The Estimation of Animal Abundance and Related Parameters</em>.
</div>
<div class="csl-entry">
Sekar, C. Chandra, and W. Edwards Deming. 1949. <span>“On a Method of Estimating Birth and Death Rates and the Extent of Registration.”</span> <em>Journal of the American Statistical Association</em> 44 (245): 101–15.
</div>
<div class="csl-entry">
Van Buuren, Stef, and Stef Van Buuren. 2012. <em>Flexible Imputation of Missing Data</em>. Vol. 10. CRC press Boca Raton, FL.
</div>
<div class="csl-entry">
Vatsalan, Dinusha, Dimitrios Karapiperis, and Vassilios S. Verykios. 2020. <span>“Privacy-Preserving Record Linkage.”</span> In <em>Encyclopedia of Big Data Technologies</em>, edited by Albert Zomaya, Javid Taheri, and Sherif Sakr, 1–10. Cham: Springer International Publishing. <a href="https://doi.org/10.1007/978-3-319-63962-8_17-2">https://doi.org/10.1007/978-3-319-63962-8_17-2</a>.
</div>
<div class="csl-entry">
Webster, Anthony J, and Richard Kemp. 2013. <span>“Estimating Omissions from Searches.”</span> <em>The American Statistician</em> 67 (2): 82–89.
</div>
<div class="csl-entry">
Winkler, William E. 2000. <em>Using the EM Algorithm for Weight Computation in the Fellegi-Sunter Model of Record Linkage</em>. US Bureau of the Census Washington, DC.
</div>
<div class="csl-entry">
Winkler, William E et al. 2006. <span>“Overview of Record Linkage and Current Research Directions.”</span> <em>Bureau of the Census</em> 25 (4): 603–23.
</div>
<div class="csl-entry">
Winkler, William E. 1990. <span>“String Comparator Metrics and Enhanced Decision Rules in the Fellegi-Sunter Model of Record Linkage.”</span> RR91/9. U.S. Bureau of the Census.
</div>
<div class="csl-entry">
Wolter, Kirk M. 1986. <span>“Some Coverage Error Models for Census Data.”</span> <em>Journal of the American Statistical Association</em> 81 (394): 338–46. <a href="https://doi.org/10.2307/2289222">https://doi.org/10.2307/2289222</a>.
</div>
<div class="csl-entry">
Zelterman, Daniel. 1988. <span>“Robust Estimation in Truncated Discrete Distributions with Application to Capture-Recapture Experiments.”</span> <em>Journal of Statistical Planning and Inference</em> 18 (2): 225–37.
</div>
</div>
</div>
</div>
<!-- </div> -->







            </section>

          </div>
        </div>
      </div>
<a href="evaluación.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/psirusteam/PESguidelines/06-Emparejamiento.rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Encuesta PostCensal.pdf", "Encuesta PostCensal.epub", "Encuesta PostCensal.mobi"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
},
"tconfig": null
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
